gpu_id: 0
multi_gpus: False
num_workers: 20
seed: 666
exp_name: 'multimodal_english'

train:
  lr: 0.0001
  batch_size: 16
  restore: False
  max_epochs: 10  
  word_dim: 300    # change

  module_dim: 512
  glove: True      # 
  k_max_frame_level: 16
  k_max_clip_level: 8
  spl_resolution: 1

val:
  flag: True

test:
  test_num: 0
  write_preds: True 
  print_sample_preds: False

dataset:
  name: 'multimodal'
  question_type: 'action'
  data_dir: 'data/multimodal/features/multimodal/action/'
  save_dir: 'results_multimodal/'

